---
- name: Ensure that the {{ iterm2_package }} package is installed
  tags: iterm2
  homebrew_cask:
    name: "{{ iterm2_package|lower }}"
    state: present
  register: iterm2_homebrew_cask

- name: Attempting to apply {{ iterm2_package }} configurations
  tags: iterm2
  osx_defaults:
    domain: "{{ iterm2_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ iterm2_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - iterm2_defaults|length > 0
    - iterm2_homebrew_cask is success
...
